/***
 *  File: a2.cpp
 *  Author: Jaroslaw Zola <jzola@buffalo.edu>
 */

// DO NOT EDIT THIS FILE !!!
// YOUR CODE MUST BE CONTAINED IN a2.hpp ONLY

#include <iostream>
#include "a2.hpp"


int main(int argc, char* argv[]) {
    sorted_sc_array A;

    {
        sorted_sc_array T;
        for (signed char c = -128; c < 127; ++c) T.insert(c);

        T = T;

        sorted_sc_array V = T;
        A = V;
    }

    const auto first = A.data();
    const auto last = first + A.size();

    auto size = A.size();
    bool res = std::is_sorted(first, last);

    if (!res || (A.size() != 255)) std::cout << "fail";
    else std::cout << "pass";

    std::cout << std::endl;

    return 0;
} // main
